
- name: CREATE volumes path
  ansible.builtin.file:
    path: "/root/hadoop/volumes"
    state: directory
    recurse: yes
    force: yes

- name: COPY
  copy:
    src: "{{ role_path }}/files"
    dest: "/root/hadoop"

- name: BUILD
  community.docker.docker_image:
    name: hadoop-pbl:1.0.0
    source: build
    build:
      #dockerfile: /root/Dockerfile
      path: "/root/hadoop/files"

- name: REMOVE FILE
  ansible.builtin.file:
    path: "/root/hadoop/files"
    state: absent

- name: RUN
  docker_container:
    name: hadoop
    image: hadoop-pbl:1.0.0
    ports:              
      
      - "9870:9870"   # (interfaz web del NameNode)
      - "8020:8020"   # (comunicación entre clientes y el NameNode)

      - "8032:8032"   # (comunicación entre clientes y el ResourceManager)
      - "8088:8088"   # (interfaz web del ResourceManager)

      - "50010:50010" # (DataNode transferencia de bloques de datos)
      - "50020:50020" # (comunicación entre DataNodes)
      - "50075:50075" # (interfaz web del DataNode)
      - "9866:9866"   # NO SEEEEE POR QUEEEE 

      - "8042:8042"   # (interfaz web del NodeManager)  
      - "2222:22"
      - "9000:9000"
     
    detach: true
    #restart_policy: always
    #volumes:
    #  - "./:/opt/hadoop"

#    Para la interfaz del NameNode: http://localhost:9870
#    Para la interfaz del ResourceManager: http://localhost:8088
#    Para la interfaz del Secondary NameNode: http://localhost:9870
#    Para la interfaz del ApplicationMaster: http://localhost:8042
#    You can access the ResourceManager Web UI at http://<container-ip>:8088, and the NodeManager Web UI at http://<container-ip>:8042
