- name: Run Cassandra container
  docker_container:
    name: cassandra
    image: cassandra:5.0
    pull: true
    ports:
      - "9042:9042"
      - "7000:7000"
      - "9160:9160"
      - "7001:7001"
      - "7199:7199"
    env:
      CASSANDRA_BROADCAST_ADDRESS: "{{ ansible_host }}"
      CASSANDRA_SEEDS: "{{ groups['biltegiak'][0] }}"
    detach: true
    #restart_policy: always
