gcp_credential  = "../PBL6.json"
gcp_project     = "murrikulum-popbl6-2024"
vm_name         = "cassandra-tmp"
vm_machine_type = "e2-micro"
vm_ssh_user     = "user"
vm_ssh_key_path = "/home/user/.ssh/gakoa.pub"
