---

- name: Proxmox-eko CT-a itzali
  hosts: pve1
  remote_user: root
  become: no
  gather_facts: no
  roles:
  - pm_ovpn_down

- name: Google Cloud Platform-eko instantzia itzali
  hosts: localhost
  roles:
  - gcp_ovpn_down
