all:
  children:
    proxmox:
      hosts:
        pve1:
          ansible_host: "{{ pm_node[0]['ip'] }}"
          ansible_ssh_private_key_file: "{{ pm_node[0]['ssh_private_key'] }}"
    ct:
      hosts:
        ovpn:
          ansible_host: "{{ ovpn_bezeroa }}"
          ansible_ssh_private_key_file: "{{ ovpn_ct_ssh_private_key }}"
